version: "3.7"

services:
  postgres:
    image: postgres:15            # Официальный образ PostgreSQL
    container_name: my-postgres   # Имя контейнера
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          # Имя пользователя БД (берем из .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Пароль (берем из .env)
      POSTGRES_DB: ${POSTGRES_DB}              # База данных, создаваемая при запуске (берем из .env)
    volumes:
      - pgdata:/var/lib/postgresql/data        # Хранилище данных
    ports:
      - "${POSTGRES_PORT}:5432"                # Проброс порта: хост:контейнер (хост берем из .env)
    networks:
      - infrastructure_default
  service-courier:
    build: .
    ports:
      - "${COURIER_PORT}:${LOCALHOST}"
    environment:
      - PORT=${LOCALHOST}
      - ORDER_SERVICE_HOST=${ORDER_SERVICE_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DELIVERY_TICKER_INTERVAL=${DELIVERY_TICKER_INTERVAL}
    networks:
      - infrastructure_default

volumes:
  pgdata:   

networks:
  infrastructure_default:
    external: true
