version: "3.7"

services:
  postgres:
    image: postgres:15            # Официальный образ PostgreSQL
    container_name: my-postgres   # Имя контейнера
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          # Имя пользователя БД (берем из .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Пароль (берем из .env)
      POSTGRES_DB: ${POSTGRES_DB}              # База данных, создаваемая при запуске (берем из .env)
    volumes:
      - pgdata:/var/lib/postgresql/data        # Хранилище данных
    ports:
      - "${POSTGRES_PORT}:5432"                # Проброс порта: хост:контейнер (хост берем из .env)
    networks:
      - infrastructure_default
  service-courier:
    build: .
    ports:
      - "${COURIER_PORT}:${LOCALHOST}"
    environment:
      - PORT=${LOCALHOST}
      - ORDER_SERVICE_HOST=${ORDER_SERVICE_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DELIVERY_TICKER_INTERVAL=${DELIVERY_TICKER_INTERVAL}
      - KAFKA_ENABLED=true
      - KAFKA_BROKERS=kafka:${KAFKA_CLIENT_PORT}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
    networks:
      - infrastructure_default
  prometheus:
    image: prom/prometheus:latest
    container_name: courier-prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - service-courier
    networks:
      - infrastructure_default

  grafana:
    image: grafana/grafana:latest
    container_name: courier-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - infrastructure_default
volumes:
  pgdata:   

networks:
  infrastructure_default:
    external: true
